services:
  postgres:
    image: postgres:15
    container_name: imobiliaria_backend
    restart: always
    environment:
      POSTGRES_USER: imobiliaria
      POSTGRES_PASSWORD: imobiliaria
      POSTGRES_DB: imobiliaria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imobiliaria-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@imobiliaria.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - imobiliaria-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  imobiliaria-network:
    driver: bridge
